### ISSUE TITLE
dd/mm/YYYY merged to mm/dd/YY in resulting .docx

### ISSUE THREAD

**Issue by Zer0ne83** [centic9/poi-mail-merge#11]
Hi guys, awesome work - very useful tool.

The one issue I have is that I am merging dates which are in Australian format (i.e. dd/mm/YYYY) from my .xlsx spreadsheet and they are somehow being transformed to US format (i.e. mm/dd/YYYY) in the 'filled' .docx. I could care less about the YYYY vs. YY output, but the inversed day/month characters are a bit of an issue!

Any ideas how I could fix this? I have ensured that both input and output merge fields (in Excel/Word) are formatted to dd/mm/YYYY and that my system (Debian 9) is set to English AU keyboard/time/geo options but I ran out of idea there.

Any help greatly appreciated!

**Comment by centic9** [comment]
Can you provide sample template and Excel-source-file? This would make it much easier to reproduce/analyze...

**Comment by Zer0ne83** [comment]
Thank you so much for your fast response centic! Yeah, sorry, that would make it a little easier. I have attached the input .xlsx, form template .docx and 'filled' (i.e. result) .docx. The info in them is obviously fake so no worries. Thanks again for your help!

[Form11Fields.xlsx](https://github.com/centic9/poi-mail-merge/files/1508805/Form11Fields.xlsx)
[F11Filled.docx](https://github.com/centic9/poi-mail-merge/files/1508806/F11Filled.docx)
[F11Itself.docx](https://github.com/centic9/poi-mail-merge/files/1508807/F11Itself.docx)

**Comment by centic9** [comment]
Hm, the following line tries to format things from the Excel file:

```
case NUMERIC:
// ensure that numerical and date values are formatted the same way as in the Excel file.
value = CellFormat.getInstance(cell.getCellStyle().getDataFormatString()).apply(cell).text;
```

When I run it with the files you provided, I get "9/21/1990" as you state. However when I edit the .XLSX file and edit the format and set a custom format of "d/m/yyyy" (in my German Excel it is actually TT/MM/JJJJ), then the resulting docx-file has the correctly formatted date of "21/9/1990". Can you try to specify the custom format here? 

It seems some locale-stuff interferes when you use one of the pre-defined date-formats and it's sometimes a bit strange what Excel does in such cases...

**Comment by Zer0ne83** [comment]
Thanks again for your help mate I really appreciate it and sorry about the late responses, I think our timezones are 'out' by a good 7-8 hours haha. I wasn't able to replicate your fix by setting custom format in Excel to d/m/yyyy which leads me to believe its something else in my setup - probably some locale setting, as you say. Regardless, its definitely not an issue with poi-mail-merge so I really appreciate you kindly donating your time! The good news is that, after thinking about it, there's absolutely no reason I can't use a .csv as the field source file for what I'm doing and poi-mail-merge handles that beautifully. The merge is faster, uses less memory and my stupid locale settings can't touch the date format haha! So problem solved... or sidestepped. In any event - I'm happy. Thanks for the help and the awesome script bro. Take care.

**Comment by centic9** [comment]
Ok, thanks for the note. So I am closing this as you found a way to make it work for you and the problem seems to originate in Apache POI itself in combination with locale specifics.
