### ISSUE TITLE
Page size

### ISSUE THREAD

**Issue by vamshins** [centic9/poi-mail-merge#5]
Hi Dominik,

Is there any way to set the page size for the document? Because, the generated document has the merged documents mixed up with the previous one. I have attached the screenshot for this.

Thanks,
Vamshi

![merge_issue](https://cloud.githubusercontent.com/assets/6483666/12311980/9d9f3420-ba18-11e5-82af-6907d0efeb23.png)

**Comment by centic9** [comment]
I will take a look if it can be handled better, for now you can try to add a page break at the end of the template, that's what worked for me when I used the functionality.

**Comment by vamshins** [comment]
Page break worked for me. Thanks!
